// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPoec65Dym990t4KbFiDuIfdzHW9_P9mE',
    appId: '1:577852943925:web:711014d5ff4e14eec0cb7c',
    messagingSenderId: '577852943925',
    projectId: 'taskmate-9519e',
    authDomain: 'taskmate-9519e.firebaseapp.com',
    storageBucket: 'taskmate-9519e.appspot.com',
    measurementId: 'G-TQK18GBF6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASY5g3K4zKlneK9qhp5li7TghSFVqW0fc',
    appId: '1:577852943925:android:bbbf1285f681cef9c0cb7c',
    messagingSenderId: '577852943925',
    projectId: 'taskmate-9519e',
    storageBucket: 'taskmate-9519e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMq4ZHZmZc8JwVATYAlH60AOnSNaGhaWE',
    appId: '1:577852943925:ios:d824f996f1b1b69ec0cb7c',
    messagingSenderId: '577852943925',
    projectId: 'taskmate-9519e',
    storageBucket: 'taskmate-9519e.appspot.com',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMq4ZHZmZc8JwVATYAlH60AOnSNaGhaWE',
    appId: '1:577852943925:ios:d824f996f1b1b69ec0cb7c',
    messagingSenderId: '577852943925',
    projectId: 'taskmate-9519e',
    storageBucket: 'taskmate-9519e.appspot.com',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPoec65Dym990t4KbFiDuIfdzHW9_P9mE',
    appId: '1:577852943925:web:cb56f7292284f284c0cb7c',
    messagingSenderId: '577852943925',
    projectId: 'taskmate-9519e',
    authDomain: 'taskmate-9519e.firebaseapp.com',
    storageBucket: 'taskmate-9519e.appspot.com',
    measurementId: 'G-DVK9FS7ZLR',
  );
}
